export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/sign-up",
    FORGOTPASSWORD: "/forgot-password",
    RESETPASSWORD: "/reset-password",
    CONFIRMEMAIL: "/confirm-email",
  },
  BLOG: "/blog",
  HOME: "/",
  USER: {
    COMMUNITY: "/user/community",
    PLAN: "/user/plans",
    COMPANYINFO: "/user/company-info",
    METRICS: "/user/metrics",
    FINANCIALS: "/user/financials",
    FUNDAMENTALS: "/user/fundamentals",
    STOCKANALYSERS: "/user/stock-analyzer",
    PROFILE: "/user/profile",
    PLANS: "/user/plans",
  },
  ADMIN: {
    USERS: "/admin/users",
    STOCKS: "/admin/stocks",
    SUBSCRIPTIONS: "/admin/subscriptions",
    ACCOUNTING: "/admin/accounting",
    FORUM: "  /admin/forum",
    BLOGMANAGER: "/admin/blog-manager",
    REPORTSANDFEEDBACKS: "/admin/reports-and-feedbacks",
    PROFILE: "/admin/profile",
    CREATEBLOG: "/admin/blog-manager/create",
  },
};
