export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/sign-up",
    FORGOTPASSWORD: "/forgot-password",
    RESETPASSWORD: "/reset-password",
    CONFIRMEMAIL: "/confirm-email",
  },
  NEWS: "/user/news",
  HOME: "/",
  USER: {
    HOME: "/user",
    COMMUNITY: "/user/community",
    PLAN: "/user/plans",
    COMPANYINFO: "/user/metrics",
    METRICS: "/user/metrics",
    FINANCIALS: "/user/financials",
    FUNDAMENTALS: "/user/fundamentals",
    STOCKANALYSERS: "/user/stock-analyzer",
    PROFILE: "/user/profile",
    SETTINGS: "/user/settings",
    PLANS: "/user/plans",
    BLOGS: "/user/blog",
    SUBSCRIPTION: "/user/subscription",
    WISHLIST: "/user/wish-list",
    SHOP: "/user/shop",
    Market: "/user/company/aapl?tab=metrics",
  },
  ADMIN: {
    USERS: "/admin/users",
    CommunityChat: "/admin/community",
    STOCKS: "/admin/stocks",
    SUBSCRIPTIONS: "/admin/subscriptions",
    ACCOUNTING: "/admin/accounting",
    FORUM: "  /admin/forum",
    BLOGMANAGER: "/admin/blog-manager",
    REPORTSANDFEEDBACKS: "/admin/reports-and-feedbacks",
    PROFILE: "/admin/profile",
    CREATEBLOG: "/admin/blog-manager/create",
  },
};
