export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/sign-up",
    FORGOTPASSWORD: "/forgot-password",
    RESETPASSWORD: "/reset-password",
    CONFIRMEMAIL: "/confirm-email",
  },
  BLOG: "/blog",
  HOME: "/",
  USER: {
    COMMUNITY: "/community",
    PLAN: "/plans",
    COMPANYINFO: "/company-info",
    METRICS: "/metrics",
    FINANCIALS: "/financials",
    FUNDAMENTALS: "/fundamentals",
    STOCKANALYSERS: "/stock-analyzer",
    PROFILE: "/profile",
    PLANS: "/plans",
  },
  ADMIN: {
    USERS: "/admin/user",
    STOCKS: "/admin/stocks",
    SUBSCRIPTIONS: "/admin/subscriptions",
    ACCOUNTING: "/admin/accounting",
    FORUM: "  /admin/forum",
    BLOGMANAGER: "/admin/blog-manager",
    REPORTSANDFEEDBACKS: "/admin/reports-and-feedbacks",
    PROFILE: "/admin/profile",
    CREATEBLOG: "/admin/blog-manager/create",
  },
};
