import type { Metadata } from "next";
import "./globals.css";
import { ChakraWrapperProvider } from "@/providers/chakraProvider";
import TopLoader from "@/components/top-loader";

export const metadata: Metadata = {
  title: "Nvidia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopLoader />
        <ChakraWrapperProvider>{children}</ChakraWrapperProvider>
      </body>
    </html>
  );
}
