export const AlldataSourceFinance = (filter: string, Data: any[]) => {
  let dataSources: {
    id: number;
    title: string;
    row1?: any;
    row2?: any;
    row3?: any;
    row4?: any;
    row5?: any;
  }[] = [];

  if (filter == "income-statements") {
    dataSources = [
      {
        id: 27,
        title: "BottomLineNetIncome",
        row1: Data[0]?.bottomLineNetIncome,
        row2: Data[1]?.bottomLineNetIncome,
        row3: Data[2]?.bottomLineNetIncome,
        row4: Data[3]?.bottomLineNetIncome,
        row5: Data[4]?.bottomLineNetIncome,
      },
      {
        id: 2,
        title: "Cik",
        row1: Data[0]?.cik,
        row2: Data[1]?.cik,
        row3: Data[2]?.cik,
        row4: Data[3]?.cik,
        row5: Data[4]?.cik,
      },
      {
        id: 12,
        title: "CostAndExpenses",
        row1: Data[0]?.costAndExpenses,
        row2: Data[1]?.costAndExpenses,
        row3: Data[2]?.costAndExpenses,
        row4: Data[3]?.costAndExpenses,
        row5: Data[4]?.costAndExpenses,
      },
      {
        id: 4,
        title: "CostOfRevenue",
        row1: Data[0]?.costOfRevenue,
        row2: Data[1]?.costOfRevenue,
        row3: Data[2]?.costOfRevenue,
        row4: Data[3]?.costOfRevenue,
        row5: Data[4]?.costOfRevenue,
      },
      {
        id: 16,
        title: "DepreciationAndAmortization",
        row1: Data[0]?.depreciationAndAmortization,
        row2: Data[1]?.depreciationAndAmortization,
        row3: Data[2]?.depreciationAndAmortization,
        row4: Data[3]?.depreciationAndAmortization,
        row5: Data[4]?.depreciationAndAmortization,
      },
      {
        id: 17,
        title: "Ebit",
        row1: Data[0]?.ebit,
        row2: Data[1]?.ebit,
        row3: Data[2]?.ebit,
        row4: Data[3]?.ebit,
        row5: Data[4]?.ebit,
      },
      {
        id: 18,
        title: "Ebitda",
        row1: Data[0]?.ebitda,
        row2: Data[1]?.ebitda,
        row3: Data[2]?.ebitda,
        row4: Data[3]?.ebitda,
        row5: Data[4]?.ebitda,
      },
      {
        id: 29,
        title: "Eps",
        row1: Data[0]?.eps,
        row2: Data[1]?.eps,
        row3: Data[2]?.eps,
        row4: Data[3]?.eps,
        row5: Data[4]?.eps,
      },
      {
        id: 30,
        title: "EpsDiluted",
        row1: Data[0]?.epsDiluted,
        row2: Data[1]?.epsDiluted,
        row3: Data[2]?.epsDiluted,
        row4: Data[3]?.epsDiluted,
        row5: Data[4]?.epsDiluted,
      },
      {
        id: 33,
        title: "FilingDate",
        row1: Data[0]?.filingDate,
        row2: Data[1]?.filingDate,
        row3: Data[2]?.filingDate,
        row4: Data[3]?.filingDate,
        row5: Data[4]?.filingDate,
      },
      {
        id: 34,
        title: "FiscalYear",
        row1: Data[0]?.fiscalYear,
        row2: Data[1]?.fiscalYear,
        row3: Data[2]?.fiscalYear,
        row4: Data[3]?.fiscalYear,
        row5: Data[4]?.fiscalYear,
      },
      {
        id: 7,
        title: "GeneralAndAdministrativeExpenses",
        row1: Data[0]?.generalAndAdministrativeExpenses,
        row2: Data[1]?.generalAndAdministrativeExpenses,
        row3: Data[2]?.generalAndAdministrativeExpenses,
        row4: Data[3]?.generalAndAdministrativeExpenses,
        row5: Data[4]?.generalAndAdministrativeExpenses,
      },
      {
        id: 5,
        title: "GrossProfit",
        row1: Data[0]?.grossProfit,
        row2: Data[1]?.grossProfit,
        row3: Data[2]?.grossProfit,
        row4: Data[3]?.grossProfit,
        row5: Data[4]?.grossProfit,
      },
      {
        id: 23,
        title: "IncomeBeforeTax",
        row1: Data[0]?.incomeBeforeTax,
        row2: Data[1]?.incomeBeforeTax,
        row3: Data[2]?.incomeBeforeTax,
        row4: Data[3]?.incomeBeforeTax,
        row5: Data[4]?.incomeBeforeTax,
      },
      {
        id: 24,
        title: "IncomeTaxExpense",
        row1: Data[0]?.incomeTaxExpense,
        row2: Data[1]?.incomeTaxExpense,
        row3: Data[2]?.incomeTaxExpense,
        row4: Data[3]?.incomeTaxExpense,
        row5: Data[4]?.incomeTaxExpense,
      },
      {
        id: 14,
        title: "InterestIncome",
        row1: Data[0]?.interestIncome,
        row2: Data[1]?.interestIncome,
        row3: Data[2]?.interestIncome,
        row4: Data[3]?.interestIncome,
        row5: Data[4]?.interestIncome,
      },
      {
        id: 15,
        title: "InterestExpense",
        row1: Data[0]?.interestExpense,
        row2: Data[1]?.interestExpense,
        row3: Data[2]?.interestExpense,
        row4: Data[3]?.interestExpense,
        row5: Data[4]?.interestExpense,
      },
      {
        id: 13,
        title: "NetInterestIncome",
        row1: Data[0]?.netInterestIncome,
        row2: Data[1]?.netInterestIncome,
        row3: Data[2]?.netInterestIncome,
        row4: Data[3]?.netInterestIncome,
        row5: Data[4]?.netInterestIncome,
      },
      {
        id: 27,
        title: "NetIncome",
        row1: Data[0]?.netIncome,
        row2: Data[1]?.netIncome,
        row3: Data[2]?.netIncome,
        row4: Data[3]?.netIncome,
        row5: Data[4]?.netIncome,
      },
      {
        id: 28,
        title: "NetIncomeDeductions",
        row1: Data[0]?.netIncomeDeductions,
        row2: Data[1]?.netIncomeDeductions,
        row3: Data[2]?.netIncomeDeductions,
        row4: Data[3]?.netIncomeDeductions,
        row5: Data[4]?.netIncomeDeductions,
      },
      {
        id: 24,
        title: "NetIncomeFromContinuingOperations",
        row1: Data[0]?.netIncomeFromContinuingOperations,
        row2: Data[1]?.netIncomeFromContinuingOperations,
        row3: Data[2]?.netIncomeFromContinuingOperations,
        row4: Data[3]?.netIncomeFromContinuingOperations,
        row5: Data[4]?.netIncomeFromContinuingOperations,
      },
      {
        id: 25,
        title: "NetIncomeFromDiscontinuedOperations",
        row1: Data[0]?.netIncomeFromDiscontinuedOperations,
        row2: Data[1]?.netIncomeFromDiscontinuedOperations,
        row3: Data[2]?.netIncomeFromDiscontinuedOperations,
        row4: Data[3]?.netIncomeFromDiscontinuedOperations,
        row5: Data[4]?.netIncomeFromDiscontinuedOperations,
      },
      {
        id: 35,
        title: "NetInterestIncome",
        row1: Data[0]?.netInterestIncome,
        row2: Data[1]?.netInterestIncome,
        row3: Data[2]?.netInterestIncome,
        row4: Data[3]?.netInterestIncome,
        row5: Data[4]?.netInterestIncome,
      },
      {
        id: 19,
        title: "NonOperatingIncomeExcludingInterest",
        row1: Data[0]?.nonOperatingIncomeExcludingInterest,
        row2: Data[1]?.nonOperatingIncomeExcludingInterest,
        row3: Data[2]?.nonOperatingIncomeExcludingInterest,
        row4: Data[3]?.nonOperatingIncomeExcludingInterest,
        row5: Data[4]?.nonOperatingIncomeExcludingInterest,
      },
      {
        id: 11,
        title: "OperatingExpenses",
        row1: Data[0]?.operatingExpenses,
        row2: Data[1]?.operatingExpenses,
        row3: Data[2]?.operatingExpenses,
        row4: Data[3]?.operatingExpenses,
        row5: Data[4]?.operatingExpenses,
      },
      {
        id: 20,
        title: "OperatingIncome",
        row1: Data[0]?.operatingIncome,
        row2: Data[1]?.operatingIncome,
        row3: Data[2]?.operatingIncome,
        row4: Data[3]?.operatingIncome,
        row5: Data[4]?.operatingIncome,
      },
      {
        id: 10,
        title: "OtherExpenses",
        row1: Data[0]?.otherExpenses,
        row2: Data[1]?.otherExpenses,
        row3: Data[2]?.otherExpenses,
        row4: Data[3]?.otherExpenses,
        row5: Data[4]?.otherExpenses,
      },
      {
        id: 26,
        title: "OtherAdjustmentsToNetIncome",
        row1: Data[0]?.otherAdjustmentsToNetIncome,
        row2: Data[1]?.otherAdjustmentsToNetIncome,
        row3: Data[2]?.otherAdjustmentsToNetIncome,
        row4: Data[3]?.otherAdjustmentsToNetIncome,
        row5: Data[4]?.otherAdjustmentsToNetIncome,
      },
      {
        id: 6,
        title: "ResearchAndDevelopmentExpenses",
        row1: Data[0]?.researchAndDevelopmentExpenses,
        row2: Data[1]?.researchAndDevelopmentExpenses,
        row3: Data[2]?.researchAndDevelopmentExpenses,
        row4: Data[3]?.researchAndDevelopmentExpenses,
        row5: Data[4]?.researchAndDevelopmentExpenses,
      },
      {
        id: 38,
        title: "Period",
        row1: Data[0]?.period,
        row2: Data[1]?.period,
        row3: Data[2]?.period,
        row4: Data[3]?.period,
        row5: Data[4]?.period,
      },
      {
        id: 39,
        title: "ReportedCurrency",
        row1: Data[0]?.reportedCurrency,
        row2: Data[1]?.reportedCurrency,
        row3: Data[2]?.reportedCurrency,
        row4: Data[3]?.reportedCurrency,
        row5: Data[4]?.reportedCurrency,
      },
      {
        id: 3,
        title: "Revenue",
        row1: Data[0]?.revenue,
        row2: Data[1]?.revenue,
        row3: Data[2]?.revenue,
        row4: Data[3]?.revenue,
        row5: Data[4]?.revenue,
      },
      {
        id: 40,
        title: "Symbol",
        row1: Data[0]?.symbol,
        row2: Data[1]?.symbol,
        row3: Data[2]?.symbol,
        row4: Data[3]?.symbol,
        row5: Data[4]?.symbol,
      },
      {
        id: 8,
        title: "SellingAndMarketingExpenses",
        row1: Data[0]?.sellingAndMarketingExpenses,
        row2: Data[1]?.sellingAndMarketingExpenses,
        row3: Data[2]?.sellingAndMarketingExpenses,
        row4: Data[3]?.sellingAndMarketingExpenses,
        row5: Data[4]?.sellingAndMarketingExpenses,
      },
      {
        id: 9,
        title: "SellingGeneralAndAdministrativeExpenses",
        row1: Data[0]?.sellingGeneralAndAdministrativeExpenses,
        row2: Data[1]?.sellingGeneralAndAdministrativeExpenses,
        row3: Data[2]?.sellingGeneralAndAdministrativeExpenses,
        row4: Data[3]?.sellingGeneralAndAdministrativeExpenses,
        row5: Data[4]?.sellingGeneralAndAdministrativeExpenses,
      },
      {
        id: 21,
        title: "TotalOtherIncomeExpensesNet",
        row1: Data[0]?.totalOtherIncomeExpensesNet,
        row2: Data[1]?.totalOtherIncomeExpensesNet,
        row3: Data[2]?.totalOtherIncomeExpensesNet,
        row4: Data[3]?.totalOtherIncomeExpensesNet,
        row5: Data[4]?.totalOtherIncomeExpensesNet,
      },
      {
        id: 31,
        title: "WeightedAverageShsOut",
        row1: Data[0]?.weightedAverageShsOut,
        row2: Data[1]?.weightedAverageShsOut,
        row3: Data[2]?.weightedAverageShsOut,
        row4: Data[3]?.weightedAverageShsOut,
        row5: Data[4]?.weightedAverageShsOut,
      },
      {
        id: 32,
        title: "WeightedAverageShsOutDil",
        row1: Data[0]?.weightedAverageShsOutDil,
        row2: Data[1]?.weightedAverageShsOutDil,
        row3: Data[2]?.weightedAverageShsOutDil,
        row4: Data[3]?.weightedAverageShsOutDil,
        row5: Data[4]?.weightedAverageShsOutDil,
      },
    ];
  } else if (filter == "balance-sheet") {
    dataSources = [
      {
        id: 1,
        title: "AccountPayables",
        row1: Data[0]?.accountPayables,
        row2: Data[1]?.accountPayables,
        row3: Data[2]?.accountPayables,
        row4: Data[3]?.accountPayables,
        row5: Data[4]?.accountPayables,
      },
      {
        id: 2,
        title: "AccountsReceivables",
        row1: Data[0]?.accountsReceivables,
        row2: Data[1]?.accountsReceivables,
        row3: Data[2]?.accountsReceivables,
        row4: Data[3]?.accountsReceivables,
        row5: Data[4]?.accountsReceivables,
      },
      {
        id: 3,
        title: "AccruedExpenses",
        row1: Data[0]?.accruedExpenses,
        row2: Data[1]?.accruedExpenses,
        row3: Data[2]?.accruedExpenses,
        row4: Data[3]?.accruedExpenses,
        row5: Data[4]?.accruedExpenses,
      },
      {
        id: 4,
        title: "AccumulatedOtherComprehensiveIncomeLoss",
        row1: Data[0]?.accumulatedOtherComprehensiveIncomeLoss,
        row2: Data[1]?.accumulatedOtherComprehensiveIncomeLoss,
        row3: Data[2]?.accumulatedOtherComprehensiveIncomeLoss,
        row4: Data[3]?.accumulatedOtherComprehensiveIncomeLoss,
        row5: Data[4]?.accumulatedOtherComprehensiveIncomeLoss,
      },
      {
        id: 5,
        title: "AdditionalPaidInCapital",
        row1: Data[0]?.additionalPaidInCapital,
        row2: Data[1]?.additionalPaidInCapital,
        row3: Data[2]?.additionalPaidInCapital,
        row4: Data[3]?.additionalPaidInCapital,
        row5: Data[4]?.additionalPaidInCapital,
      },
      {
        id: 6,
        title: "CashAndCashEquivalents",
        row1: Data[0]?.cashAndCashEquivalents,
        row2: Data[1]?.cashAndCashEquivalents,
        row3: Data[2]?.cashAndCashEquivalents,
        row4: Data[3]?.cashAndCashEquivalents,
        row5: Data[4]?.cashAndCashEquivalents,
      },
      {
        id: 7,
        title: "CashAndShortTermInvestments",
        row1: Data[0]?.cashAndShortTermInvestments,
        row2: Data[1]?.cashAndShortTermInvestments,
        row3: Data[2]?.cashAndShortTermInvestments,
        row4: Data[3]?.cashAndShortTermInvestments,
        row5: Data[4]?.cashAndShortTermInvestments,
      },
      {
        id: 8,
        title: "CommonStock",
        row1: Data[0]?.commonStock,
        row2: Data[1]?.commonStock,
        row3: Data[2]?.commonStock,
        row4: Data[3]?.commonStock,
        row5: Data[4]?.commonStock,
      },
      {
        id: 9,
        title: "DeferredRevenue",
        row1: Data[0]?.deferredRevenue,
        row2: Data[1]?.deferredRevenue,
        row3: Data[2]?.deferredRevenue,
        row4: Data[3]?.deferredRevenue,
        row5: Data[4]?.deferredRevenue,
      },
      {
        id: 10,
        title: "DeferredRevenueNonCurrent",
        row1: Data[0]?.deferredRevenueNonCurrent,
        row2: Data[1]?.deferredRevenueNonCurrent,
        row3: Data[2]?.deferredRevenueNonCurrent,
        row4: Data[3]?.deferredRevenueNonCurrent,
        row5: Data[4]?.deferredRevenueNonCurrent,
      },
      {
        id: 11,
        title: "DeferredTaxLiabilitiesNonCurrent",
        row1: Data[0]?.deferredTaxLiabilitiesNonCurrent,
        row2: Data[1]?.deferredTaxLiabilitiesNonCurrent,
        row3: Data[2]?.deferredTaxLiabilitiesNonCurrent,
        row4: Data[3]?.deferredTaxLiabilitiesNonCurrent,
        row5: Data[4]?.deferredTaxLiabilitiesNonCurrent,
      },
      {
        id: 12,
        title: "Goodwill",
        row1: Data[0]?.goodwill,
        row2: Data[1]?.goodwill,
        row3: Data[2]?.goodwill,
        row4: Data[3]?.goodwill,
        row5: Data[4]?.goodwill,
      },
      {
        id: 13,
        title: "GoodwillAndIntangibleAssets",
        row1: Data[0]?.goodwillAndIntangibleAssets,
        row2: Data[1]?.goodwillAndIntangibleAssets,
        row3: Data[2]?.goodwillAndIntangibleAssets,
        row4: Data[3]?.goodwillAndIntangibleAssets,
        row5: Data[4]?.goodwillAndIntangibleAssets,
      },
      {
        id: 14,
        title: "IntangibleAssets",
        row1: Data[0]?.intangibleAssets,
        row2: Data[1]?.intangibleAssets,
        row3: Data[2]?.intangibleAssets,
        row4: Data[3]?.intangibleAssets,
        row5: Data[4]?.intangibleAssets,
      },
      {
        id: 15,
        title: "Inventory",
        row1: Data[0]?.inventory,
        row2: Data[1]?.inventory,
        row3: Data[2]?.inventory,
        row4: Data[3]?.inventory,
        row5: Data[4]?.inventory,
      },
      {
        id: 16,
        title: "LongTermInvestments",
        row1: Data[0]?.longTermInvestments,
        row2: Data[1]?.longTermInvestments,
        row3: Data[2]?.longTermInvestments,
        row4: Data[3]?.longTermInvestments,
        row5: Data[4]?.longTermInvestments,
      },
      {
        id: 17,
        title: "MinorityInterest",
        row1: Data[0]?.minorityInterest,
        row2: Data[1]?.minorityInterest,
        row3: Data[2]?.minorityInterest,
        row4: Data[3]?.minorityInterest,
        row5: Data[4]?.minorityInterest,
      },
      {
        id: 18,
        title: "NetDebt",
        row1: Data[0]?.netDebt,
        row2: Data[1]?.netDebt,
        row3: Data[2]?.netDebt,
        row4: Data[3]?.netDebt,
        row5: Data[4]?.netDebt,
      },
      {
        id: 19,
        title: "NetReceivables",
        row1: Data[0]?.netReceivables,
        row2: Data[1]?.netReceivables,
        row3: Data[2]?.netReceivables,
        row4: Data[3]?.netReceivables,
        row5: Data[4]?.netReceivables,
      },
      {
        id: 20,
        title: "OtherAssets",
        row1: Data[0]?.otherAssets,
        row2: Data[1]?.otherAssets,
        row3: Data[2]?.otherAssets,
        row4: Data[3]?.otherAssets,
        row5: Data[4]?.otherAssets,
      },
      {
        id: 21,
        title: "OtherCurrentAssets",
        row1: Data[0]?.otherCurrentAssets,
        row2: Data[1]?.otherCurrentAssets,
        row3: Data[2]?.otherCurrentAssets,
        row4: Data[3]?.otherCurrentAssets,
        row5: Data[4]?.otherCurrentAssets,
      },
      {
        id: 22,
        title: "OtherCurrentLiabilities",
        row1: Data[0]?.otherCurrentLiabilities,
        row2: Data[1]?.otherCurrentLiabilities,
        row3: Data[2]?.otherCurrentLiabilities,
        row4: Data[3]?.otherCurrentLiabilities,
        row5: Data[4]?.otherCurrentLiabilities,
      },
      {
        id: 23,
        title: "OtherLiabilities",
        row1: Data[0]?.otherLiabilities,
        row2: Data[1]?.otherLiabilities,
        row3: Data[2]?.otherLiabilities,
        row4: Data[3]?.otherLiabilities,
        row5: Data[4]?.otherLiabilities,
      },
      {
        id: 24,
        title: "OtherNonCurrentAssets",
        row1: Data[0]?.otherNonCurrentAssets,
        row2: Data[1]?.otherNonCurrentAssets,
        row3: Data[2]?.otherNonCurrentAssets,
        row4: Data[3]?.otherNonCurrentAssets,
        row5: Data[4]?.otherNonCurrentAssets,
      },
      {
        id: 25,
        title: "OtherNonCurrentLiabilities",
        row1: Data[0]?.otherNonCurrentLiabilities,
        row2: Data[1]?.otherNonCurrentLiabilities,
        row3: Data[2]?.otherNonCurrentLiabilities,
        row4: Data[3]?.otherNonCurrentLiabilities,
        row5: Data[4]?.otherNonCurrentLiabilities,
      },
      {
        id: 26,
        title: "OtherPayables",
        row1: Data[0]?.otherPayables,
        row2: Data[1]?.otherPayables,
        row3: Data[2]?.otherPayables,
        row4: Data[3]?.otherPayables,
        row5: Data[4]?.otherPayables,
      },
      {
        id: 27,
        title: "OtherReceivables",
        row1: Data[0]?.otherReceivables,
        row2: Data[1]?.otherReceivables,
        row3: Data[2]?.otherReceivables,
        row4: Data[3]?.otherReceivables,
        row5: Data[4]?.otherReceivables,
      },

      {
        id: 28,
        title: "PreferredStock",
        row1: Data[0]?.preferredStock,
        row2: Data[1]?.preferredStock,
        row3: Data[2]?.preferredStock,
        row4: Data[3]?.preferredStock,
        row5: Data[4]?.preferredStock,
      },
      {
        id: 29,
        title: "Prepaids",
        row1: Data[0]?.prepaids,
        row2: Data[1]?.prepaids,
        row3: Data[2]?.prepaids,
        row4: Data[3]?.prepaids,
        row5: Data[4]?.prepaids,
      },

      {
        id: 30,
        title: "PropertyPlantEquipmentNet",
        row1: Data[0]?.propertyPlantEquipmentNet,
        row2: Data[1]?.propertyPlantEquipmentNet,
        row3: Data[2]?.propertyPlantEquipmentNet,
        row4: Data[3]?.propertyPlantEquipmentNet,
        row5: Data[4]?.propertyPlantEquipmentNet,
      },
      {
        id: 31,
        title: "RetainedEarnings",
        row1: Data[0]?.retainedEarnings,
        row2: Data[1]?.retainedEarnings,
        row3: Data[2]?.retainedEarnings,
        row4: Data[3]?.retainedEarnings,
        row5: Data[4]?.retainedEarnings,
      },
      {
        id: 32,
        title: "ShortTermDebt",
        row1: Data[0]?.shortTermDebt,
        row2: Data[1]?.shortTermDebt,
        row3: Data[2]?.shortTermDebt,
        row4: Data[3]?.shortTermDebt,
        row5: Data[4]?.shortTermDebt,
      },
      {
        id: 33,
        title: "ShortTermInvestments",
        row1: Data[0]?.shortTermInvestments,
        row2: Data[1]?.shortTermInvestments,
        row3: Data[2]?.shortTermInvestments,
        row4: Data[3]?.shortTermInvestments,
        row5: Data[4]?.shortTermInvestments,
      },

      {
        id: 34,
        title: "TaxAssets",
        row1: Data[0]?.taxAssets,
        row2: Data[1]?.taxAssets,
        row3: Data[2]?.taxAssets,
        row4: Data[3]?.taxAssets,
        row5: Data[4]?.taxAssets,
      },
      {
        id: 35,
        title: "TaxPayables",
        row1: Data[0]?.taxPayables,
        row2: Data[1]?.taxPayables,
        row3: Data[2]?.taxPayables,
        row4: Data[3]?.taxPayables,
        row5: Data[4]?.taxPayables,
      },
      {
        id: 36,
        title: "TotalAssets",
        row1: Data[0]?.totalAssets,
        row2: Data[1]?.totalAssets,
        row3: Data[2]?.totalAssets,
        row4: Data[3]?.totalAssets,
        row5: Data[4]?.totalAssets,
      },
      {
        id: 37,
        title: "TotalCurrentAssets",
        row1: Data[0]?.totalCurrentAssets,
        row2: Data[1]?.totalCurrentAssets,
        row3: Data[2]?.totalCurrentAssets,
        row4: Data[3]?.totalCurrentAssets,
        row5: Data[4]?.totalCurrentAssets,
      },
      {
        id: 38,
        title: "TotalCurrentLiabilities",
        row1: Data[0]?.totalCurrentLiabilities,
        row2: Data[1]?.totalCurrentLiabilities,
        row3: Data[2]?.totalCurrentLiabilities,
        row4: Data[3]?.totalCurrentLiabilities,
        row5: Data[4]?.totalCurrentLiabilities,
      },

      {
        id: 39,
        title: "TotalInvestments",
        row1: Data[0]?.totalInvestments,
        row2: Data[1]?.totalInvestments,
        row3: Data[2]?.totalInvestments,
        row4: Data[3]?.totalInvestments,
        row5: Data[4]?.totalInvestments,
      },
      {
        id: 40,
        title: "TotalLiabilities",
        row1: Data[0]?.totalLiabilities,
        row2: Data[1]?.totalLiabilities,
        row3: Data[2]?.totalLiabilities,
        row4: Data[3]?.totalLiabilities,
        row5: Data[4]?.totalLiabilities,
      },
      {
        id: 41,
        title: "TotalLiabilitiesAndTotalEquity",
        row1: Data[0]?.totalLiabilitiesAndTotalEquity,
        row2: Data[1]?.totalLiabilitiesAndTotalEquity,
        row3: Data[2]?.totalLiabilitiesAndTotalEquity,
        row4: Data[3]?.totalLiabilitiesAndTotalEquity,
        row5: Data[4]?.totalLiabilitiesAndTotalEquity,
      },
      {
        id: 42,
        title: "TotalNonCurrentAssets",
        row1: Data[0]?.totalNonCurrentAssets,
        row2: Data[1]?.totalNonCurrentAssets,
        row3: Data[2]?.totalNonCurrentAssets,
        row4: Data[3]?.totalNonCurrentAssets,
        row5: Data[4]?.totalNonCurrentAssets,
      },
      {
        id: 43,
        title: "TotalNonCurrentLiabilities",
        row1: Data[0]?.totalNonCurrentLiabilities,
        row2: Data[1]?.totalNonCurrentLiabilities,
        row3: Data[2]?.totalNonCurrentLiabilities,
        row4: Data[3]?.totalNonCurrentLiabilities,
        row5: Data[4]?.totalNonCurrentLiabilities,
      },
      {
        id: 44,
        title: "TotalPayables",
        row1: Data[0]?.totalPayables,
        row2: Data[1]?.totalPayables,
        row3: Data[2]?.totalPayables,
        row4: Data[3]?.totalPayables,
        row5: Data[4]?.totalPayables,
      },
      {
        id: 45,
        title: "TotalStockholdersEquity",
        row1: Data[0]?.totalStockholdersEquity,
        row2: Data[1]?.totalStockholdersEquity,
        row3: Data[2]?.totalStockholdersEquity,
        row4: Data[3]?.totalStockholdersEquity,
        row5: Data[4]?.totalStockholdersEquity,
      },
      {
        id: 46,
        title: "TreasuryStock",
        row1: Data[0]?.treasuryStock,
        row2: Data[1]?.treasuryStock,
        row3: Data[2]?.treasuryStock,
        row4: Data[3]?.treasuryStock,
        row5: Data[4]?.treasuryStock,
      },
      {
        id: 47,
        title: "CapitalLeaseObligations",
        row1: Data[0]?.capitalLeaseObligations,
        row2: Data[1]?.capitalLeaseObligations,
        row3: Data[2]?.capitalLeaseObligations,
        row4: Data[3]?.capitalLeaseObligations,
        row5: Data[4]?.capitalLeaseObligations,
      },
      {
        id: 48,
        title: "CapitalLeaseObligationsCurrent",
        row1: Data[0]?.capitalLeaseObligationsCurrent,
        row2: Data[1]?.capitalLeaseObligationsCurrent,
        row3: Data[2]?.capitalLeaseObligationsCurrent,
        row4: Data[3]?.capitalLeaseObligationsCurrent,
        row5: Data[4]?.capitalLeaseObligationsCurrent,
      },
      {
        id: 49,
        title: "symbol",
        row1: Data[0]?.symbol,
        row2: Data[1]?.symbol,
        row3: Data[2]?.symbol,
        row4: Data[3]?.symbol,
        row5: Data[4]?.symbol,
      },
      {
        id: 50,
        title: "TotalDebt",
        row1: Data[0]?.totalDebt,
        row2: Data[1]?.totalDebt,
        row3: Data[2]?.totalDebt,
        row4: Data[3]?.totalDebt,
        row5: Data[4]?.totalDebt,
      },
      {
        id: 51,
        title: "totalEquity",
        row1: Data[0]?.totalEquity,
        row2: Data[1]?.totalEquity,
        row3: Data[2]?.totalEquity,
        row4: Data[3]?.totalEquity,
        row5: Data[4]?.totalEquity,
      },
      {
        id: 52,
        title: "ReportedCurrency",
        row1: Data[0]?.reportedCurrency,
        row2: Data[1]?.reportedCurrency,
        row3: Data[2]?.reportedCurrency,
        row4: Data[3]?.reportedCurrency,
        row5: Data[4]?.reportedCurrency,
      },
      {
        id: 53,
        title: "Period",
        row1: Data[0]?.period,
        row2: Data[1]?.period,
        row3: Data[2]?.period,
        row4: Data[3]?.period,
        row5: Data[4]?.period,
      },
      {
        id: 54,
        title: "Date",
        row1: Data[0]?.date,
        row2: Data[1]?.date,
        row3: Data[2]?.date,
        row4: Data[3]?.date,
        row5: Data[4]?.date,
      },
      {
        id: 55,
        title: "FilingDate",
        row1: Data[0]?.filingDate,
        row2: Data[1]?.filingDate,
        row3: Data[2]?.filingDate,
        row4: Data[3]?.filingDate,
        row5: Data[4]?.filingDate,
      },
      {
        id: 56,
        title: "FiscalYear",
        row1: Data[0]?.fiscalYear,
        row2: Data[1]?.fiscalYear,
        row3: Data[2]?.fiscalYear,
        row4: Data[3]?.fiscalYear,
        row5: Data[4]?.fiscalYear,
      },
      {
        id: 57,
        title: "OtherTotalStockholdersEquity",
        row1: Data[0]?.otherTotalStockholdersEquity,
        row2: Data[1]?.otherTotalStockholdersEquity,
        row3: Data[2]?.otherTotalStockholdersEquity,
        row4: Data[3]?.otherTotalStockholdersEquity,
        row5: Data[4]?.otherTotalStockholdersEquity,
      },
      {
        id: 58,
        title: "Cik",
        row1: Data[0]?.cik,
        row2: Data[1]?.cik,
        row3: Data[2]?.cik,
        row4: Data[3]?.cik,
        row5: Data[4]?.cik,
      },
    ];
  } else if (filter == "cashflow") {
    dataSources = [
      {
        id: 1,
        title: "AccountPayables",
        row1: Data[0]?.accountsPayables,
        row2: Data[1]?.accountsPayables,
        row3: Data[2]?.accountsPayables,
        row4: Data[3]?.accountsPayables,
        row5: Data[4]?.accountsPayables,
      },
      {
        id: 2,
        title: "AccountsReceivables",
        row1: Data[0]?.accountsReceivables,
        row2: Data[1]?.accountsReceivables,
        row3: Data[2]?.accountsReceivables,
        row4: Data[3]?.accountsReceivables,
        row5: Data[4]?.accountsReceivables,
      },
      {
        id: 3,
        title: "AcquisitionsNet",
        row1: Data[0]?.acquisitionsNet,
        row2: Data[1]?.acquisitionsNet,
        row3: Data[2]?.acquisitionsNet,
        row4: Data[3]?.acquisitionsNet,
        row5: Data[4]?.acquisitionsNet,
      },

      {
        id: 4,
        title: "CashAtBeginningOfPeriod",
        row1: Data[0]?.cashAtBeginningOfPeriod,
        row2: Data[1]?.cashAtBeginningOfPeriod,
        row3: Data[2]?.cashAtBeginningOfPeriod,
        row4: Data[3]?.cashAtBeginningOfPeriod,
        row5: Data[4]?.cashAtBeginningOfPeriod,
      },
      {
        id: 5,
        title: "CashAtEndOfPeriod",
        row1: Data[0]?.cashAtEndOfPeriod,
        row2: Data[1]?.cashAtEndOfPeriod,
        row3: Data[2]?.cashAtEndOfPeriod,
        row4: Data[3]?.cashAtEndOfPeriod,
        row5: Data[4]?.cashAtEndOfPeriod,
      },
      {
        id: 6,
        title: "ChangeInWorkingCapital",
        row1: Data[0]?.changeInWorkingCapital,
        row2: Data[1]?.changeInWorkingCapital,
        row3: Data[2]?.changeInWorkingCapital,
        row4: Data[3]?.changeInWorkingCapital,
        row5: Data[4]?.changeInWorkingCapital,
      },
      {
        id: 7,
        title: "CommonDividendsPaid",
        row1: Data[0]?.commonDividendsPaid,
        row2: Data[1]?.commonDividendsPaid,
        row3: Data[2]?.commonDividendsPaid,
        row4: Data[3]?.commonDividendsPaid,
        row5: Data[4]?.commonDividendsPaid,
      },
      {
        id: 8,
        title: "CommonStockIssuance",
        row1: Data[0]?.commonStockIssuance,
        row2: Data[1]?.commonStockIssuance,
        row3: Data[2]?.commonStockIssuance,
        row4: Data[3]?.commonStockIssuance,
        row5: Data[4]?.commonStockIssuance,
      },
      {
        id: 9,
        title: "CommonStockRepurchased",
        row1: Data[0]?.commonStockRepurchased,
        row2: Data[1]?.commonStockRepurchased,
        row3: Data[2]?.commonStockRepurchased,
        row4: Data[3]?.commonStockRepurchased,
        row5: Data[4]?.commonStockRepurchased,
      },
      {
        id: 10,
        title: "CapitalExpenditure",
        row1: Data[0]?.capitalExpenditure,
        row2: Data[1]?.capitalExpenditure,
        row3: Data[2]?.capitalExpenditure,
        row4: Data[3]?.capitalExpenditure,
        row5: Data[4]?.capitalExpenditure,
      },
      {
        id: 11,
        title: "DeferredIncomeTax",
        row1: Data[0]?.deferredIncomeTax,
        row2: Data[1]?.deferredIncomeTax,
        row3: Data[2]?.deferredIncomeTax,
        row4: Data[3]?.deferredIncomeTax,
        row5: Data[4]?.deferredIncomeTax,
      },
      {
        id: 12,
        title: "DepreciationAndAmortization",
        row1: Data[0]?.depreciationAndAmortization,
        row2: Data[1]?.depreciationAndAmortization,
        row3: Data[2]?.depreciationAndAmortization,
        row4: Data[3]?.depreciationAndAmortization,
        row5: Data[4]?.depreciationAndAmortization,
      },

      {
        id: 13,
        title: "EffectOfForexChangesOnCash",
        row1: Data[0]?.effectOfForexChangesOnCash,
        row2: Data[1]?.effectOfForexChangesOnCash,
        row3: Data[2]?.effectOfForexChangesOnCash,
        row4: Data[3]?.effectOfForexChangesOnCash,
        row5: Data[4]?.effectOfForexChangesOnCash,
      },
      {
        id: 14,
        title: "FreeCashFlow",
        row1: Data[0]?.freeCashFlow,
        row2: Data[1]?.freeCashFlow,
        row3: Data[2]?.freeCashFlow,
        row4: Data[3]?.freeCashFlow,
        row5: Data[4]?.freeCashFlow,
      },

      {
        id: 15,
        title: "IncomeTaxesPaid",
        row1: Data[0]?.incomeTaxesPaid,
        row2: Data[1]?.incomeTaxesPaid,
        row3: Data[2]?.incomeTaxesPaid,
        row4: Data[3]?.incomeTaxesPaid,
        row5: Data[4]?.incomeTaxesPaid,
      },
      {
        id: 16,
        title: "Inventory",
        row1: Data[0]?.inventory,
        row2: Data[1]?.inventory,
        row3: Data[2]?.inventory,
        row4: Data[3]?.inventory,
        row5: Data[4]?.inventory,
      },
      {
        id: 17,
        title: "InterestPaid",
        row1: Data[0]?.interestPaid,
        row2: Data[1]?.interestPaid,
        row3: Data[2]?.interestPaid,
        row4: Data[3]?.interestPaid,
        row5: Data[4]?.interestPaid,
      },
      {
        id: 18,
        title: "InvestmentsInPropertyPlantAndEquipment",
        row1: Data[0]?.investmentsInPropertyPlantAndEquipment,
        row2: Data[1]?.investmentsInPropertyPlantAndEquipment,
        row3: Data[2]?.investmentsInPropertyPlantAndEquipment,
        row4: Data[3]?.investmentsInPropertyPlantAndEquipment,
        row5: Data[4]?.investmentsInPropertyPlantAndEquipment,
      },
      {
        id: 19,
        title: "LongTermNetDebtIssuance",
        row1: Data[0]?.longTermNetDebtIssuance,
        row2: Data[1]?.longTermNetDebtIssuance,
        row3: Data[2]?.longTermNetDebtIssuance,
        row4: Data[3]?.longTermNetDebtIssuance,
        row5: Data[4]?.longTermNetDebtIssuance,
      },
      {
        id: 20,
        title: "NetCashProvidedByFinancingActivities",
        row1: Data[0]?.netCashProvidedByFinancingActivities,
        row2: Data[1]?.netCashProvidedByFinancingActivities,
        row3: Data[2]?.netCashProvidedByFinancingActivities,
        row4: Data[3]?.netCashProvidedByFinancingActivities,
        row5: Data[4]?.netCashProvidedByFinancingActivities,
      },
      {
        id: 21,
        title: "NetCashProvidedByInvestingActivities",
        row1: Data[0]?.netCashProvidedByInvestingActivities,
        row2: Data[1]?.netCashProvidedByInvestingActivities,
        row3: Data[2]?.netCashProvidedByInvestingActivities,
        row4: Data[3]?.netCashProvidedByInvestingActivities,
        row5: Data[4]?.netCashProvidedByInvestingActivities,
      },
      {
        id: 22,
        title: "NetCashProvidedByOperatingActivities",
        row1: Data[0]?.netCashProvidedByOperatingActivities,
        row2: Data[1]?.netCashProvidedByOperatingActivities,
        row3: Data[2]?.netCashProvidedByOperatingActivities,
        row4: Data[3]?.netCashProvidedByOperatingActivities,
        row5: Data[4]?.netCashProvidedByOperatingActivities,
      },
      {
        id: 23,
        title: "NetChangeInCash",
        row1: Data[0]?.netChangeInCash,
        row2: Data[1]?.netChangeInCash,
        row3: Data[2]?.netChangeInCash,
        row4: Data[3]?.netChangeInCash,
        row5: Data[4]?.netChangeInCash,
      },
      {
        id: 24,
        title: "NetCommonStockIssuance",
        row1: Data[0]?.netCommonStockIssuance,
        row2: Data[1]?.netCommonStockIssuance,
        row3: Data[2]?.netCommonStockIssuance,
        row4: Data[3]?.netCommonStockIssuance,
        row5: Data[4]?.netCommonStockIssuance,
      },
      {
        id: 25,
        title: "NetDebtIssuance",
        row1: Data[0]?.netDebtIssuance,
        row2: Data[1]?.netDebtIssuance,
        row3: Data[2]?.netDebtIssuance,
        row4: Data[3]?.netDebtIssuance,
        row5: Data[4]?.netDebtIssuance,
      },
      {
        id: 26,
        title: "NetDividendsPaid",
        row1: Data[0]?.netDividendsPaid,
        row2: Data[1]?.netDividendsPaid,
        row3: Data[2]?.netDividendsPaid,
        row4: Data[3]?.netDividendsPaid,
        row5: Data[4]?.netDividendsPaid,
      },
      {
        id: 27,
        title: "NetIncome",
        row1: Data[0]?.netIncome,
        row2: Data[1]?.netIncome,
        row3: Data[2]?.netIncome,
        row4: Data[3]?.netIncome,
        row5: Data[4]?.netIncome,
      },
      {
        id: 28,
        title: "NetPreferredStockIssuance",
        row1: Data[0]?.netPreferredStockIssuance,
        row2: Data[1]?.netPreferredStockIssuance,
        row3: Data[2]?.netPreferredStockIssuance,
        row4: Data[3]?.netPreferredStockIssuance,
        row5: Data[4]?.netPreferredStockIssuance,
      },
      {
        id: 29,
        title: "NetStockIssuance",
        row1: Data[0]?.netStockIssuance,
        row2: Data[1]?.netStockIssuance,
        row3: Data[2]?.netStockIssuance,
        row4: Data[3]?.netStockIssuance,
        row5: Data[4]?.netStockIssuance,
      },
      {
        id: 30,
        title: "OperatingCashFlow",
        row1: Data[0]?.operatingCashFlow,
        row2: Data[1]?.operatingCashFlow,
        row3: Data[2]?.operatingCashFlow,
        row4: Data[3]?.operatingCashFlow,
        row5: Data[4]?.operatingCashFlow,
      },
      {
        id: 31,
        title: "OtherFinancingActivities",
        row1: Data[0]?.otherFinancingActivities,
        row2: Data[1]?.otherFinancingActivities,
        row3: Data[2]?.otherFinancingActivities,
        row4: Data[3]?.otherFinancingActivities,
        row5: Data[4]?.otherFinancingActivities,
      },
      {
        id: 32,
        title: "OtherInvestingActivities",
        row1: Data[0]?.otherInvestingActivities,
        row2: Data[1]?.otherInvestingActivities,
        row3: Data[2]?.otherInvestingActivities,
        row4: Data[3]?.otherInvestingActivities,
        row5: Data[4]?.otherInvestingActivities,
      },
      {
        id: 33,
        title: "OtherNonCashItems",
        row1: Data[0]?.otherNonCashItems,
        row2: Data[1]?.otherNonCashItems,
        row3: Data[2]?.otherNonCashItems,
        row4: Data[3]?.otherNonCashItems,
        row5: Data[4]?.otherNonCashItems,
      },
      {
        id: 34,
        title: "OtherWorkingCapital",
        row1: Data[0]?.otherWorkingCapital,
        row2: Data[1]?.otherWorkingCapital,
        row3: Data[2]?.otherWorkingCapital,
        row4: Data[3]?.otherWorkingCapital,
        row5: Data[4]?.otherWorkingCapital,
      },
      {
        id: 35,
        title: "PreferredDividendsPaid",
        row1: Data[0]?.preferredDividendsPaid,
        row2: Data[1]?.preferredDividendsPaid,
        row3: Data[2]?.preferredDividendsPaid,
        row4: Data[3]?.preferredDividendsPaid,
        row5: Data[4]?.preferredDividendsPaid,
      },
      {
        id: 36,
        title: "PurchasesOfInvestments",
        row1: Data[0]?.purchasesOfInvestments,
        row2: Data[1]?.purchasesOfInvestments,
        row3: Data[2]?.purchasesOfInvestments,
        row4: Data[3]?.purchasesOfInvestments,
        row5: Data[4]?.purchasesOfInvestments,
      },
      {
        id: 37,
        title: "SalesMaturitiesOfInvestments",
        row1: Data[0]?.salesMaturitiesOfInvestments,
        row2: Data[1]?.salesMaturitiesOfInvestments,
        row3: Data[2]?.salesMaturitiesOfInvestments,
        row4: Data[3]?.salesMaturitiesOfInvestments,
        row5: Data[4]?.salesMaturitiesOfInvestments,
      },
      {
        id: 38,
        title: "ShortTermNetDebtIssuance",
        row1: Data[0]?.shortTermNetDebtIssuance,
        row2: Data[1]?.shortTermNetDebtIssuance,
        row3: Data[2]?.shortTermNetDebtIssuance,
        row4: Data[3]?.shortTermNetDebtIssuance,
        row5: Data[4]?.shortTermNetDebtIssuance,
      },
      {
        id: 39,
        title: "StockBasedCompensation",
        row1: Data[0]?.stockBasedCompensation,
        row2: Data[1]?.stockBasedCompensation,
        row3: Data[2]?.stockBasedCompensation,
        row4: Data[3]?.stockBasedCompensation,
        row5: Data[4]?.stockBasedCompensation,
      },
      {
        id: 40,
        title: "FiscalYear",
        row1: Data[0]?.fiscalYear,
        row2: Data[1]?.fiscalYear,
        row3: Data[2]?.fiscalYear,
        row4: Data[3]?.fiscalYear,
        row5: Data[4]?.fiscalYear,
      },
      {
        id: 41,
        title: "Period",
        row1: Data[0]?.period,
        row2: Data[1]?.period,
        row3: Data[2]?.period,
        row4: Data[3]?.period,
        row5: Data[4]?.period,
      },
      {
        id: 42,
        title: "CapitalExpenditure",
        row1: Data[0]?.capitalExpenditure,
        row2: Data[1]?.capitalExpenditure,
        row3: Data[2]?.capitalExpenditure,
        row4: Data[3]?.capitalExpenditure,
        row5: Data[4]?.capitalExpenditure,
      },
      {
        id: 43,
        title: "filingDate",
        row1: Data[0]?.filingDate,
        row2: Data[1]?.filingDate,
        row3: Data[2]?.filingDate,
        row4: Data[3]?.filingDate,
        row5: Data[4]?.filingDate,
      },
      {
        id: 44,
        title: "Cik",
        row1: Data[0]?.cik,
        row2: Data[1]?.cik,
        row3: Data[2]?.cik,
        row4: Data[3]?.cik,
        row5: Data[4]?.cik,
      },
      {
        id: 45,
        title: "Date",
        row1: Data[0]?.date,
        row2: Data[1]?.date,
        row3: Data[2]?.date,
        row4: Data[3]?.date,
        row5: Data[4]?.date,
      },
    ];
  }
  return dataSources;
};

export const DataSourceAnalyzer = (Data: any) => {
  const dataSources = [
    {
      id: 1,
      year1: Data?.roic?.first,
      year10: Data?.roic?.ten,
      year5: Data?.roic?.fifth,
      feature: "ROIC",
      category: "roic",
    },
    {
      id: 2,
      year1: Data?.revGrowth?.first,
      year10: Data?.revGrowth?.ten,
      year5: Data?.revGrowth?.fifth,
      feature: "Rev. Growth %",
      category: "revGrowth",
    },
    {
      id: 3,
      year1: Data?.profitMargin?.first,
      year10: Data?.profitMargin?.ten,
      year5: Data?.profitMargin?.fifth,
      feature: "Profit Margin",
      category: "profitMargin",
    },
    {
      id: 4,
      year1: Data?.freeCashFlowMargin?.first,
      year10: Data?.freeCashFlowMargin?.ten,
      year5: Data?.freeCashFlowMargin?.fifth,
      feature: "Free Cash Flow Margin",
      category: "freeCashFlowMargin",
    },
    {
      id: 5,
      year1: Data?.peRatio?.first,
      year10: Data?.peRatio?.ten,
      year5: Data?.peRatio?.fifth,
      feature: "P/E",
      category: "peRatio",
    },
    {
      id: 6,
      year1: Data?.pfcf?.first,
      year10: Data?.pfcf?.ten,
      year5: Data?.pfcf?.fifth,
      feature: "P/FCF",
      category: "pfcf",
    },
    {
      id: 6,
      year1: 0,
      year10: 0,
      year5: 0,
      feature: "Desired Annual Return",
      category: "desiredAnnReturn",
    },
  ];
  return dataSources;
};
export const DataSourceAnalyzerResult = (Data: any) => {
  const dataSources = [
    {
      feature: "Discounted Earnings Value",
      low: Data?.discountedEarningsValue.low,
      medium: Data?.discountedEarningsValue.mid,
      high: Data?.discountedEarningsValue.high,
      id: 1,
    },
    {
      feature: "Discounted Free Cash Flow Value",
      low: Data?.discountedFreeCashFlowValue.low,
      medium: Data?.discountedFreeCashFlowValue.mid,
      high: Data?.discountedFreeCashFlowValue.high,
      id: 2,
    },
    {
      feature: "Current Price Return",
      low: 117.83,
      medium: 117.83,
      high: 117.83,
      id: 3,
    },
  ];
  return dataSources;
};

/**
 * Converts an ISO date string to a human-readable date string.
 * @param isoDateString - The ISO date string (e.g., "2024-04-16T16:33:17").
 * @param locale - The locale to use for formatting (default is 'en-US').
 * @param options - Optional formatting options for the date.
 * @returns A human-readable date string.
 */
export function formatDateToHumanReadable(
  isoDateString: string,
  locale: string = "en-US",
  options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "long",
    day: "numeric",
  }
): string {
  const date = new Date(isoDateString);
  return date.toLocaleDateString(locale, options);
}
